### ISSUE TITLE
Dutch translation: auto-import from Weblate failed

### ISSUE THREAD

**Issue by y20k** [y20k/escapepod#16]
A couple of days ago @vistaus put up a Dutch translation on [Weblate](https://hosted.weblate.org/projects/escapepod/android-app/nl/) (Thanks!! BTW). The auto-export to GitHub failed to work so far. Usually a new `string.xml` resource would be created under `app/src/main/res/values-nl`.

@comradekingu Do you have an idea, on what's wrong with the configuration of either the GitHub-Repo, or the Weblate account? (related: #13). 

As far as I can see this project is configured with the same parameters as my other projects ([Trackbook](https://github.com/y20k/trackbook), [Transistor](https://github.com/y20k/transistor)) are.

**Comment by comradekingu** [comment]
@y20k https://hosted.weblate.org/user/kingu/ is not admin for https://hosted.weblate.org/languages/nb_NO/trackbook/ , but I can have a look if you make it so.

**Comment by comradekingu** [comment]
AFAIK nothing is getting imported. Did you add the Weblate-bot?

**Comment by y20k** [comment]
I only have an iPad at hand at the moment. I will drop in a couple of screenshots from the GitHub configuration ...

![503C8462-DE19-4B56-A467-CED01C560AB7](https://user-images.githubusercontent.com/9103935/69991985-0346f800-1549-11ea-9e69-03437f314c19.png)
![68DBDC0D-DB53-47B6-B99E-7A16F6864175](https://user-images.githubusercontent.com/9103935/69991988-0346f800-1549-11ea-8a77-131ae129ca96.png)
![7470A538-4C57-4694-BE1E-8A6DA1F1F886](https://user-images.githubusercontent.com/9103935/69991989-03df8e80-1549-11ea-9f70-8395235f590c.png)

**Comment by y20k** [comment]
> I can have a look if you make it so

**Comment by comradekingu** [comment]
In https://hosted.weblate.org/settings/escapepod/android-app/#vcs

- Changed VCS from "GitHub" to "Git" (though I don't think that makes a difference i saw other Android apps on GitHub with just "Git".
- Added push address  
- Changed from "rebasing" to "merge"

#Fixes 16

(Also changed website to http://www.y20k.org/escapepod/ in https://hosted.weblate.org/settings/escapepod/ to make it consistent with other y20k projects.)

@Vistaus Type AltGr+. to use ellipsis → "…" instead of tripledot → "...". :)

**Comment by Vistaus** [comment]
@comradekingu Thanks for the tip! :)

**Comment by y20k** [comment]
@comradekingu Many thanks. You got it working!
