### ISSUE TITLE
can't download podcast with vpn

### ISSUE THREAD

**Issue by BloodyMerise** [y20k/escapepod#17]
When i try to download a podcast with vpn on, i get a pop-up “offline Connect to the internet“.

i can add new podcast lists (i can see the icons and latest episodes), and internet works with other apps.

It seems the refresh of the lists is also working as i don't have the pop up when i do so.

If i disable “block connections without vpn" in android vpn settings and try right after, the problem persists. 

If i disconnect from vpn altogether, i can download and play the podcast just fine.

I'm using android 9, oxygen OS 9.0.9 and protonvpn v1.4.52. Escapepod is 0.7.12 from F-droid.

Please let me know if you need more info ? Btw, i really like the minimalistic approach of your app. It's slick, well done 👍

**Comment by y20k** [comment]
Hi @BloodyMerise and thanks for the bug report.

I tried the following steps to reproduce the problem.

1. connected device to the internet using WiFi 
2. installed a VPN via system settings 
3. activated the VPN over the running WiFi connection
4. updated the podcast collection (pull-to-refresh on the list)

That did not result in an error. New episodes showed up and were downloaded. :-/ So what now? 

Can you maybe post a more detailed description, of what I can do to reproduce the problem.

**Comment by BloodyMerise** [comment]
Thanks for the quick feedback! 

With vpn on, i can add podcasts from any rss link Ive tried. They appear in the list, i have the five last episodes titles etc. But when i click on the cloud with an arrow pointing down (which i assume is the download feature), i immediately get the pop up “offline connect to internet". Here is a screenshot showing the pop up when i tapped the cloud of the last item at the bottom.

![Screenshot_20191204-190412](https://user-images.githubusercontent.com/45909730/70137552-200a3980-16c9-11ea-85e8-179e19accf24.jpg)

**Comment by y20k** [comment]
When one taps the download button, the app currently checks

1. WiFi connection available -> download immediately
2. Cellular connection available -> ask user ("Download Anyway?")
3. none of the above -> show error

When I turn off WiFi AND turn on a VPN on Android 10, I do not get an error, only the "Download Anyway?" dialog. Strangely your system behaves differently ... probably due to a different implementation of the VPN feature.

Looking further into it, I found, that it is possible to check, if the device is connected via VPN. Since it is not always possible to determine, if the VPN is running on top of WiFi or on top of Cellular, the app should ask the user ("Download Anyway?").

So Escapepod in the future will check (in that order):

1. WiFi connection available -> download immediately
2. Cellular connection available -> ask user ("Download Anyway?")
3. VPN connection available -> ask user ("Download Anyway?")
4. none of the above -> show error

**Comment by BloodyMerise** [comment]
Hi, just got the update from f-droid, i now get the pop up 'download anyway?' when i download podcasts with vpn. And i can play the poscast right after... AWESOME

Thank you so much!
