### ISSUE TITLE
View more than the 5 most recent episodes

### ISSUE THREAD

**Issue by marissarousseau** [y20k/escapepod#18]
While I understand Escapepod's intention is to be simple and bare bones, it would be nice to be able to access the entire feed of a podcast rather than the five most recent episodes. Some podcasts are chronologically-based meaning the user is restricted from listening to them since they cannot listen past the five most recent episodes.

**Comment by y20k** [comment]
Hi @marissarousseau,

I thought about that problem, too, when I was sketching out the single-window UI for Escapepod. I tried, but did not find a suitable solution. There must be a reason why most podcast players have list of podcasts and for each podcast a separate list of episodes. 😄 

I expect Escapepod to remain a niche product. It will never be able to compete against full featured players like Antennapod. I am the only developer. I need to keep the app maintainable. Hence the single-window approach.

But on the other hand: one should never say never. Maybe once I got all the kinks worked out and I find the time a way to access ALL episodes would be a nice addition.

**Comment by marissarousseau** [comment]
That's completely understandable. I figured that was the case since Escapepod is intended to only have a single window. I definitely appreciate it's simplicity. Hopefully in the future a solution can be found.

**Comment by ernestask** [comment]
Having only a single screen is orthogonal to this issue. One possible solution could be pagination, either with a button or a gesture (though these are rarely discoverable), another could be simple expansion of the list, but then lots of scrolling is to be expected.

**Comment by y20k** [comment]
I am closing this issue. I may come back to this, because - as previously mentioned - I would like to see more episodes in the UI, too. But so far I don't have a convincing way to display them, given the self-imposed constraints for the app. 

I added the issue to the list [Previous discussions and feature requests](https://github.com/y20k/escapepod/issues/24), because I somehow have the feeling it may come up again :-)

**Comment by folknor** [comment]
I just bought https://absolutelymental.com/ and it's the first time I've bought a podcast where I want access to the entire library (it's just 11 short episodes.)

I've read the thread, and I've read #24, and I realise this is free and open source (and I also realise you've not asked for help on how to design this), but I'll be bold and say my piece anyway;
1. When I first click "OLDER EPISODES", it expands down, and "OLDER EPISODES" is still there at the bottom as a click target to contract again; (a) it's not obvious that it's a click target at all and that it will do anything if clicked again, and (b) there's no way for a user to know whether clicking it again will further expand the list or contract it before clicking it, (c) it sometimes changes to "HIDE OLDER EPISODES", but not always, and I can reliably change it back (removing "HIDE") by closing and reopening the app and sometimes just by switching back and forth between apps
2. If I was implementing it within the constraints you've set for the app, I'd add a second action to an already-expanded list that opened a popup dialog with a scrollable list, like in the attached image
![658f7a6115e14696a093f5ba109e24f47be865f2_jpg_85](https://user-images.githubusercontent.com/233791/118413725-47bc4a00-b690-11eb-9415-043644ddbb81.jpg)



Thanks for an excellent app!

**Comment by y20k** [comment]
Hi @folknor 

every now and then I too wish that Escapepod can display more than 5 episodes. The only solution I came up with so far was very similar to yours: A pop-up with a scrollable list of all episodes. The next problem then would be: how should the app handle downloaded episodes? There is a "danger" that this kind of UI would result in Escapepod keeping too many files. So viable solution might be: Make the episodes in the pop-up only available via streaming. 

> it sometimes changes to "HIDE OLDER EPISODES", but not always

I noticed that bug a couple of days ago, too. The commit [e47a82f](https://github.com/y20k/escapepod/commit/e47a82ff2a06f448ce5bd7f0433ead58564f2cd4) fixes the problem (at least for me so far). The fix will be part of v1.0.5.


> Material Design guidelines say that buttons are a "call to action" that should be in ALL CAPS, Google ignores this completely - I can't think of a single example where they use all caps in a button themselves. With good reason - I can expand on that if you want.

Oh. Interesting. Yes, I would like to read your take on this.

**Comment by folknor** [comment]
It's not really my take as such, I try to refer to science and in this case government policy also conveniently follows science, as does the UX design guidelines for all major platforms, including GNOME, Apple, Android (though like I said the documentation says otherwise, Google ignores it completely in all their apps), and Windows.

https://developer.gnome.org/hig/stable/typography.html.en: `Never capitalize every letter in a word or sentence.`
https://develop.kde.org/hig/components/navigation/pushbutton/: `Use title style capitalization for the label.`
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2016788/: `There is conventional wisdom, supported by some evidence and logic within the fields of typography and cognitive science, that asserts that text set in mixed upper- and lower-case is more legible than all upper-case (all capital letters).`
https://developer.apple.com/design/human-interface-guidelines/macos/buttons/push-buttons/: `Use title-case for push button titles. Capitalize every word except articles, coordinating conjunctions, and prepositions of four or fewer letters.`
https://design-system.service.gov.uk/components/button/: `Write button text in sentence case`
https://www.vegvesen.no/_attachment/69071/binary/964084: (PDF download, translated to English) `4-2.5 Text must uppercase the first letter and lowercase other letters, unless otherwise indicated for special signs.`
https://readabilityguidelines.co.uk/grammar-points/capital-letters/#3-use-sentence-case-for-buttons: `Use sentence case for buttons. It's easier to scan.`

And so forth. This is settled science. If I am ever in doubt, frankly I refer to the gnome HIG, and if it doesn't specify on the topic I'm concerned about, I first try to change my approach ("design") entirely.

As the NIH (US government) link elaborates; 

> Typographers generally point to the fact that word shape is more distinctive with mixed- and lower-case than it is with all upper-case, a virtue that results from the fact that all upper-case characters are the same height and have no ascenders and descenders, whereas lower case characters, which have both ascenders and descenders vary in both height and average position, arguably making words constructed with them more distinctive due to more variation in the height of word contours

**Comment by therealrobster** [comment]
Why not just a "Load more" button and each time you press it, it loads 5 more episodes?  Super simple, doesn't change the interface at all and we can use the application.  As it is, I had to change to another app that lets me listen to episode 1 first, then onward.

**Comment by y20k** [comment]
Problem is that any solution, where you can download older episodes, must also come with a solution on how to organize those downloads - see an older [comment](https://github.com/y20k/escapepod/issues/18#issuecomment-842111802).

**Comment by therealrobster** [comment]
I would say that people who want to list to anything that's older than 5 episodes long can't use the app, at all, is a real issue.  I mean, if a user can't even use the app (as in literally can no use the app) then what's the point of it?  I don't mean to sound harsh, but that is a key question.  I want to listen to podcasts X, Y and Z.  I've come here from say iPhone land and am setting up in this new software.  I try it, go to retrieve the episodes I haven't caught up on yet (they are chronological) and I can't.  I can only get the last 5.  I have to move on.  This is what I did as there is just no way to use the software.  It's what I would call a 'blocker'.  I am blocked as a user.  I can NOT access my content.  Close.  Uninstall.

**Comment by y20k** [comment]
@therealrobster You absolutely correct. If you want to listen to older episodes or want to go through the whole back catalog of a podcast, Escapepod is a failure. I basically created Escapepod just for myself and gave it to the public afterwards. I have no problem with users uninstalling the app. 

My goals for this app were: 

- I want to listen the latest episode(s) of my favorite podcasts
- I want a simple single screen interface

That leave out a lot of feature that the bigger podcasts apps have. No episode back catalog is probably the biggest disappointment for most users. But also the app has no discovery feature, no playlists, no favorites, no cloud sync ...

**Comment by y20k** [comment]
I know this is probably not what you would have liked, but since [v1.0.5](https://github.com/y20k/escapepod/releases/tag/v1.0.5) the app has a hidden "Streaming" view. This view lists **ALL EPIDODES** and allows streaming them.

You can access the streaming view via a long press on "Hide older episodes".

<a href="https://user-images.githubusercontent.com/9103935/157244632-5508c88e-5701-4a1c-b38c-15251a9e9eb9.png"><img src="https://user-images.githubusercontent.com/9103935/157244632-5508c88e-5701-4a1c-b38c-15251a9e9eb9.png" width="360" /></a>

**Comment by folknor** [comment]
First of all I want to say - mostly because I think it's funny - that this is very counter-intuitive. I would never have discovered that feature naturally :-P

But most of all I want to say thank you - for both the feature and informing us of it! Thank you!

**Comment by Consolatis** [comment]
I didn't naturally discover this feature either but now I use it all the time. Thanks!

Maybe the header for a podcast could just include a button to open the streaming view.  
You can also stream the latest episodes after all and thus this feature is not strictly connected to "older episodes".

An additional setting to prevent automatic downloading would be a nice addition to the streaming feature.

**Comment by y20k** [comment]
My plan is to eventually add a streaming icon at the bottom left of an expanded episode list. Right now the streaming feature is too unpolished. Several features are still missing. For example:

- the "Add to up-next" feature does not yet work
- the user interface does not show whether the playback of the currently playing episode is offline or streaming

So for now I need / want to keep this feature "hidden".
