### ISSUE TITLE
Search results aren't visible

### ISSUE THREAD

**Issue by Nihisil** [y20k/escapepod#21]
I'm getting these gray rectangles on any search query. If I click on the one, the app just closes.

Android 9, app version is 0.8.5 (from F-Droid).

![image](https://user-images.githubusercontent.com/475367/71777316-0b2b0980-2fd9-11ea-9691-f1b984f2e161.png)

**Comment by y20k** [comment]
Hi @Nihisil 

Thankyou for finding this! Strangely enough the problem seems not to be an issue on my device. I will have to look into this.

**Comment by y20k** [comment]
Hi @Nihisil 

thanks again for reporting this. That was a super-important bug. It is fixed in the current release [v0.8.6](https://github.com/y20k/escapepod/releases/tag/v0.8.6). If anyone is interested... it was the Proguard minimizing feature that bit me here - see [commit](https://github.com/y20k/escapepod/commit/e2006fd2401b944f2d31d2f2836b2f0e1b9babfa) for details.

There remains an issue with the results for the specific [search term](https://gpodder.net/search/?q=radio-t) you used. None of the results can be added to Escapepod. Which one of the [results](https://gpodder.net/search/?q=radio-t) do you want to add? I can have a look into this.

:vulcan_salute:

**Comment by Nihisil** [comment]
@y20k thanks for the quick fix! I can confirm that there is search results in 0.8.6 version now. Don't worry about search results, I have added podcast feed (got it from the podcast website) manually and it is working fine.
