### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by NathanBnm** [y20k/escapepod#22]
Hi!
Could you add French on Weblate? I would be pleased to contribute!

**Comment by y20k** [comment]
Hi @NathanBnm,

Having a French translation would be super awesome :+1: :+1:. I must admit though, that I have not used Weblate myself to translate the app. So I am not sure, if I am giving the correct instructions, but: There is a button `Start new translation` on the page https://hosted.weblate.org/projects/escapepod/android-app/ - I think that should do the trick.

**Comment by NathanBnm** [comment]
Thanks for your reply. I just saw there is a button. I'll do that soon. But in fact, I have no way to know every context of the app 'cause I can't install it (See #23), so some translation could be inexact depending of the context 🤔

**Comment by y20k** [comment]
Okay. I understand that that sucks :-/

**Comment by NathanBnm** [comment]
@y20k translation is now done. But i left a few comments on Weblate. Could you please check.

**Comment by y20k** [comment]
@NathanBnm Wow. Thank you! I must say ... you cannot profit from your own translation work, because I refuse to make Escapepod available on Android 6 ... and you still did it ... Hats off! I wish I could repay this somehow. If you ever come to Stuttgart, I will buy you 🍺 and 🍔. 

> Could you please check them?

Sure. Give me a couple of days.
