### ISSUE TITLE
External SD Card

### ISSUE THREAD

**Issue by rudism** [y20k/escapepod#27]
I've noticed that escapepod saves to internal memory even if the phone has an SD card inserted.

I think a sane default could be something like how the [Libby app](https://help.libbyapp.com/6118.htm) works--it will save to the external SD card if one exists and fall back to internal memory if not (there is no configuration for this, it handles it automagically).

**Comment by y20k** [comment]
I would like to have that option, too. I added the `help wanted` tag.

Currently Escapepod stores all files in its own app directory, which is a reliable environment.

If Escapepod would use the "normal" storage and would for example create a folder "Escapepod" on the same level as the "Download" folder... then everything would get way more complicated. In this environment the app need special permissions that can be revoked by the user, files do not have reliable path etc. (Some interesting articles on that can be found on the [Commonsware blog](https://commonsware.com/blog/2019/10/08/storage-situation-external-storage.html)) 

And that would be still the "normal", non-sd-card storage. With [removable storage](https://commonsware.com/blog/2019/10/11/storage-situation-removable-storage.html) (sd-card) the situation even gets a bit more complicated.

My fear is that implementing support for sd-card storage would amount a lot of work and comprehensive testing. Also the changes introduced in Android 10 may not be the last changes - so supporting sd-card storage could be an ongoing effort.

And since Escapepod is just a free time one-person project (=me), I think I will not implement this in the foreseeable future. 

If an interested developer wants to help out here, your help would be very welcome (after all, I still would like to have this feature). But please contact me first regarding implementation details.

**Comment by y20k** [comment]
Closing this issue - but it is still listed here:
* [Previous discussions and feature requests](https://github.com/y20k/escapepod/issues/24)
