### ISSUE TITLE
[FR] import M3U as a podcast

### ISSUE THREAD

**Issue by ildar** [y20k/escapepod#28]
maybe as simple as a static not updatable list

**Comment by y20k** [comment]
I thought of something similar lately. What about having a `My Episodes` folder somewhere on storage. Files in that folder would show up in an extra Podcast Card named My Episodes in the podcast list.

I am not actively planing to implement this right now, since Escapepod is just a hobby project and I am a bit time-constraint. But I would like to have this feature. I am currently still working on stability and smaller bugs. As soon as I feel confident that the app has a solid foundation, it is time for new features. 

If in the meantime someone else wants to tackle this issue, please contact me first, so that we can discuss implementation details.

**Comment by ildar** [comment]
Meanwhile made up a PC converter: https://github.com/ildar/m3u2rss

**Comment by y20k** [comment]
Closing this issue - but it is still listed here:
* [Previous discussions and feature requests](https://github.com/y20k/escapepod/issues/24)
