### ISSUE TITLE
Not possible to listen podcast

### ISSUE THREAD

**Issue by yabb85** [y20k/escapepod#32]
The podcast are not listenable.

1. Open Escapepod
2. Add new podcast https://feed.pippa.io/public/shows/5dfa5ce4ab5c3f6204bb95fd
![Screenshot_2020-04-01-15-27-15-796_org y20k escapepod](https://user-images.githubusercontent.com/5111497/78345583-1b359380-759e-11ea-9fec-b2e0a0282239.jpg)
3. Unfold to see old release
![Screenshot_2020-04-01-15-22-45-335_org y20k escapepod](https://user-images.githubusercontent.com/5111497/78345698-428c6080-759e-11ea-9cf8-962c6b9d24b2.jpg)
4. Click on cloud to download podcast
5. Download is in progress
![Screenshot_2020-04-01-15-27-21-530_org y20k escapepod](https://user-images.githubusercontent.com/5111497/78345727-51731300-759e-11ea-8349-7355f0cd52fe.jpg)

But after download i have always the same screen at step 3, and i don't know where is the file downloaded.

**Expected behavior**
1. possibility to listen the downloaded content
2. move the downloaded file in standard directory, for example:
- /Music
- /Download
- /Android/media/

**Device:**
 - Device: Xiaomi Mi 9T
 - OS: MIUI GLobal 11.0.4 / Android 10 QKQ
 - Escapepod 0.9.1

**Comment by y20k** [comment]
Hi @yabb85 

the episodes of the podcast, you mentioned, refuse to be downloaded, because the media files of this podcast have the wrong encoding. The server sends them as `application/octet-stream`. Usually MP3s have the content type `audio/mpeg`.

Escapepod needs the correct content type to decide what to do with a file it gets handed over from the system's download manager.

I had a similar problem myself. A solution that may sound not promising, has worked for me with. I wrote a short email to the podcast's publisher. They fixed the content type.

A solution for the Escapepod app would be: if the content type check fails, try to read the first couple of bytes to find out, if a file is an MP3, JPG, PNG, etc.

As for your second request

> move the downloaded file in standard directory

Android is becoming increasingly "hostile" (in lack of a better word) towards apps that want to access a shared directory. (privacy and security-wise this is a good direction.) Suggested reading would be some random post about storage on [The CommomsBlog](https://commonsware.com/blog/archive.html) :cowboy_hat_face:  Anyway. There are still ways to make your suggestion possible, but keeping the files in `/Android/data/org.y20k.escapepod/files/` saves me as the developer a lot of hassle. So since Escapepod is a one-person fun project this likely not happen too soon, sorry.

**Comment by yabb85** [comment]
Hi,

Thanks you very much for tour answers ans explanations.
Good Luck with this amazing project.

Best regards
