### ISSUE TITLE
Upgrading from 0.9.5 to 1.0.1 deleted all my podcasts

### ISSUE THREAD

**Issue by windsurfer** [y20k/escapepod#70]
Upon upgrading to 1.0.1 from f-droid, all my podcasts were missing.

**To Reproduce**
1. Install version 0.9.5 from f-droid
2. Add a podcast
3. Upgrade to 1.0.1
4. Podcasts deleted

**Device:**
 - Device: F(x)tec Pro1
 - OS: Lineage OS 17.1

**Comment by y20k** [comment]
@windsurfer 

Thanks for reporting. And I am very sorry that you lost all your podcasts!! 

The update from v0.9.x to v1.0.x was pretty significant, because the way podcasts are stored changed: They were stored in a JSON file and they are now stored in a database. I added an import function that adds all your existing podcasts to the database. And I tested this part of the app a lot.

I again tested the import with the steps to reproduce, you noted. But on my device the podcasts were carried over from v0.9.5.

So I am a bit lost here without reproduction steps - sorry. :-/

In any case: I would not recommend using v1.0.1. This version can crash when using search (see #65). Better install v1.0.2 or v1.0.3 which I will publish later today.

**Comment by windsurfer** [comment]
Updating directly to 1.0.2 from 0.9.5 had no issues for me :)

**Comment by bryankaplan** [comment]
This just happened to me on 1.0.2. I have no idea what all of my podcasts were. Would it really have been so hard to migrate from JSON to a DB? Is there any way I can recover the JSON?

**Comment by y20k** [comment]
Hi. 

You might want to search the folder "collection" on your device and try to save any JSON or OPML files. The latter can be imported via settings.

/Android/data/org.y20k.escapepod/files/collection

**Comment by d7415** [comment]
I also experienced this upgrading from 0.9.5 to 1.0.3. While this appears to be quite rare and it's a bit late, it may be worth retroactively adding it to the release notes - that would have saved me about an hour last night trying to find the issue, (unsuccessfully) recover the feeds list and then trying to remember all of the subscriptions I'd had (including those that are between seasons so I've not listened to them in months).

**Comment by y20k** [comment]
Hi @d7415 
The [ImportHelper.kt](https://github.com/y20k/escapepod/blob/master/app/src/main/java/org/y20k/escapepod/legacy/ImportHelper.kt) should handle the import from v0.9.5 without any problems. I tested it on my phone and in an emulator dozens of times. Sadly I still have no idea which conditions must be met, for it to fail. I think adding an warning screen to the next version (which would be v1.0.5) is be more than two month too late. :-/

**Comment by d7415** [comment]
> I think adding an warning screen to the next version (which would be v1.0.5) is be more than two month too late. :-/

Yeah. I just meant going to the releases page and editing the 1.0.1 notes to include it, but you're right, I'm not sure how much benefit that would have as it's only for the tiny cross section of users who both haven't upgraded from 0.9.5 yet and do bother to read release notes.
