### ISSUE TITLE
App crashes after adding a podcast

### ISSUE THREAD

**Issue by TarekJ03** [y20k/escapepod#71]
**Describe the bug**
Trying to add the Podcast "Logbuch:Netzpolitik", the add suddenly crashes without adding it.

**To Reproduce**
1. Open the search
2. Search for "Logbuch:Netzpolitik" with Podcastindex.org
3. Click on "add"
4. Crash

**Expected behavior**
Adding the specified podcast without a crash.

**Screenshots**
I don't believe screenshots to be necessary here.

**Device:**
 - Device: Samsung Galaxy S9 (Exynos)
 - OS: /e/-OS
 - Version 0.15-o-20210317106363-stable-starlte

**Additional context**
Other Podcasts could be added without issues.

**Comment by y20k** [comment]
Hi, good evening. I am afk at the moment, I cannot really look into this right now, but the bug you are describing sounds familiar. It is fixed in v1.0.3. The crash happend, when the app wants to display an Error message. This message is shown, when the RSS parser did not extract any episodes from a given feed. I need to check what it is that trips up Escapepod's parser. I guess it is because the feed https://logbuch-netzpolitik.de/feed/m4a delivers m4a/aac files. Escapepod does not support that format yet.

**Comment by TarekJ03** [comment]
Alright, thanks a lot! I'll wait until v1.0.3 is on F-Droid.

**Comment by y20k** [comment]
@TarekJ03 

Just FYI. The mentioned podcast has an MP3 feed, too. That may solve the problem for you. You can add the address directly to Escapepod. 
https://feeds.metaebene.me/lnp/mp3

I still need to implement m4a support, though :-)

**Comment by TarekJ03** [comment]
Thanks for the link! Will do :D
