### ISSUE TITLE
Change display order.

### ISSUE THREAD

**Issue by qzwongo** [y20k/escapepod#96]
Thanks for the time and effort you put into this project.  I'm hoping escapepod can replace my old preferred player (Carcast) which has been abandoned, and is starting to fail me in a few ways as the landscape changes around it.  

I like the simple interface, making it fairly easy to use in the car with only a few taps.  

In the vein of a simple interface with minimal taps, I would like to see the _oldest, downloaded, unplayed_ episode at the top of the display.  This involves a few changes, ordered below in my order of preference:
1. Show feeds with downloaded episodes ahead of feeds with no downloads
2. For the single displayed episode for each feed, show the oldest downloaded episode (if any downloaded), rather than the latest episode.
3. Track "played" status of downloads (maybe this is not new?)
4. Re-order feeds dynamically as episodes are played

Again, many thanks for the app.  I'd love to see the enhancements above, either all at once or piecemeal.

**Comment by y20k** [comment]
Hi @qzwongo, hope you are well. And thank you for your idea / suggestion.

The current way of ordering podcasts and their episodes is:

- the podcast with the most recently published episode is on top of the list.
- the episodes within a podcast are sorted by publishing date

I really think, that this view makes a lot of sense for a default view. That is probably because I use the app in that way. :smiley: I want to see, what is new.

> I would like to see the _oldest, downloaded, unplayed_ episode at the top of the display.

You seem to disagree :smiley:. I guess everyone has a slightly different approach / usage profile. I imagine the combination: use in a car (out of WiFi range) and maybe with Auto-Download turned off ... will result in the wish to only see downloaded episodes. So because two people might have two different usage patterns, other podcast apps offer more than one view into the podcast collection of a user. 

I think of Escapepod's niche as the podcast player with just one 'screen'. And given that I think **newest first** is the more natural default view than **oldest, downloaded, unplayed**. I really think the view you suggested should be a secondary view. I also think that 'oldest, downloaded, unplayed' needs explanation. If Escapepod for example had a menu / an in-app navigation, then _newest first_ would be the default 'My Podcasts' view, and the app would offer views like 'Downloaded', 'Oldest First', 'Favorites Only' ...

Anyway. Escapepod is not that app. And I am sorry, but as long as Escapepod stays positioned as the minimalist podcast app with only a single screen, it will not get alternative views into the podcast collection of a user. I hope you are not too disappointed.
